services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/tmp
    networks:
      - backend

volumes:
  api_volume:

networks:
  backend:
    driver: bridge
